# Generated by Django 4.2.1 on 2023-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tixapp", "0003_remove_user_city_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="No City", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
        migrations.AddField(
            model_name="venue",
            name="address",
            field=models.TextField(default="No Address Specified"),
        ),
        migrations.AddField(
            model_name="venue",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venue",
            name="city",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
