# Generated by Django 4.2.1 on 2023-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tixapp", "0005_show_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
