# Generated by Django 4.2.1 on 2023-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tixapp",
            "0006_remove_user_username_alter_user_city_alter_user_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(),
        ),
    ]
